version: '3.8'

services:
  react:
    build: ./demo-frontend-2/  # Path to your React app's Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - flask-app
    networks:
      - app-network
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=YoutubeDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    user: root
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80

    volumes:
      - ./pgadmin:/var/lib/pgadmin

    networks:
      - app-network

  flask-app:
    build: ./
    ports:
      - "8000:5020"
    depends_on:
      - db
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge